default-scheme = "base24-dracula"
hooks = ["bash ~/.config/tinted-theming/tinty/hooks/quickshell-colors.sh"]

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = "source \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-yazi"
name = "tinted-yazi"
themes-dir = "flavors"
hook = '''
cp -f "$TINTY_THEME_FILE_PATH" "$HOME/.config/yazi/flavors/tinted-scheme.yazi/flavor.toml"
'''

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-terminal"
themes-dir = "themes/kitty"
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-nvim"
path = "https://github.com/tinted-theming/tinted-nvim"
themes-dir = "colors"
hook = "echo $TINTY_SCHEME_ID > ~/.cache/tinted-nvim-current-scheme"
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-fzf"
path = "https://github.com/tinted-theming/tinted-fzf"
themes-dir = "sh"
hook = "cp -f \"$TINTY_THEME_FILE_PATH\" ~/.cache/tinted-fzf-theme.sh"
supported-systems = ["base16", "base24"]
