#!/usr/bin/env bash
set -euo pipefail

# Must match programs.obsidian.vaults.<name> in
# shared/graphical/modules/obsidian/obsidian.nix.
vault="$HOME/Documents/Obsidian"
out="$vault/.obsidian/snippets/tinty.css"

# set -e aborts the whole script on any simple command that returns
# nonzero, INCLUDING inside a `var=$(fn)` assignment and bare `test && echo`
# chains - only an `if`'s condition (or a `... || true`/`continue`) is
# exempt. Every helper here ends by explicitly returning 0 so an unset
# base24 slot (expected on base16-only schemes) can't kill the run.
hex() {
  local slot="$1"
  local r_var="TINTY_SCHEME_PALETTE_BASE${slot}_HEX_R"
  local g_var="TINTY_SCHEME_PALETTE_BASE${slot}_HEX_G"
  local b_var="TINTY_SCHEME_PALETTE_BASE${slot}_HEX_B"
  local r="${!r_var:-}"
  local g="${!g_var:-}"
  local b="${!b_var:-}"
  if [ -n "$r" ] && [ -n "$g" ] && [ -n "$b" ]; then
    echo "#${r}${g}${b}"
  fi
  return 0
}

# Prints "  --name: value;" iff value is non-empty; no-op (and never a
# failing exit status) otherwise.
emit() {
  local name="$1"
  local value="$2"
  if [ -n "$value" ]; then
    echo "  --${name}: ${value};"
  fi
  return 0
}

# "RR, GG, BB" decimal - Obsidian's --color-*-rgb vars feed rgba() effects
# (hover/translucent overlays) and need decimal, not the hex forms above.
rgb_decimal() {
  local hexval="${1#\#}"
  if [ -n "$hexval" ]; then
    printf '%d, %d, %d' "0x${hexval:0:2}" "0x${hexval:2:2}" "0x${hexval:4:2}"
  fi
  return 0
}

# Nothing to do if the vault isn't there yet (e.g. first activation before
# the vault directory exists) - don't fail the whole tinty hook chain.
[ -d "$vault" ] || exit 0

mkdir -p "$(dirname "$out")"

{
  echo "/* Generated by tinty (obsidian-colors hook) - do not edit by hand. */"
  # Matches Obsidian's own selector for its dark palette (confirmed against
  # its bundled CSS) so this wins the cascade without needing !important -
  # snippets load after core/theme CSS. Light mode isn't handled - base16
  # schemes are dark-oriented and that's what's actually in use here.
  echo ".theme-dark {"

  # base16 role mapping (chriskempson/base16 spec) onto Obsidian's own
  # --color-base-NN grayscale + named accent variables. There's no official
  # base16/base24<->Obsidian mapping to follow - this is our own convention.
  base00=$(hex 00) # bg
  base01=$(hex 01) # lighter bg (status bar, gutters)
  base02=$(hex 02) # selection bg
  base03=$(hex 03) # comments / muted
  base04=$(hex 04) # dark fg
  base05=$(hex 05) # default fg
  base06=$(hex 06) # light fg
  base07=$(hex 07) # lightest bg
  base08=$(hex 08) # red
  base09=$(hex 09) # orange
  base0A=$(hex 0A) # yellow
  base0B=$(hex 0B) # green
  base0C=$(hex 0C) # cyan
  base0D=$(hex 0D) # blue - also doubles as the primary accent, see below
  base0E=$(hex 0E) # purple
  base0F=$(hex 0F) # brown - no direct Obsidian slot, unused below

  # base24 extension: base10/base11 are darker-than-base00 background
  # shades (base11 darkest). Only present for base24 schemes - base16-only
  # schemes leave these empty and we fall back to base00, same as before.
  base10=$(hex 10)
  base11=$(hex 11)
  darkest="${base11:-${base00}}"
  darker="${base10:-${base00}}"
  # base12-17 (bright red/yellow/green/cyan/blue/magenta) have no
  # prescribed editor role in the base24 spec, and Obsidian doesn't expose
  # a natural "bright accent" slot distinct from the ones below - left
  # unused rather than forcing a made-up mapping.

  # 10-step grayscale ladder, darkest to lightest - base24 schemes get a
  # distinct hex per step; base16-only schemes collapse the darkest two
  # (00/10) down to base00, same limitation as any base16-only consumer.
  emit "color-base-00" "$darkest"
  emit "color-base-10" "$darker"
  emit "color-base-20" "$base00"
  emit "color-base-25" "$base01"
  emit "color-base-30" "$base02"
  emit "color-base-35" "$base03"
  emit "color-base-40" "$base04"
  emit "color-base-50" "$base05"
  emit "color-base-60" "$base06"
  emit "color-base-70" "$base06"
  emit "color-base-100" "$base07"

  for pair in "red:$base08" "orange:$base09" "yellow:$base0A" "green:$base0B" \
    "cyan:$base0C" "blue:$base0D" "purple:$base0E" "pink:$base0E"; do
    name="${pair%%:*}"
    value="${pair#*:}"
    [ -n "$value" ] || continue
    echo "  --color-${name}: ${value};"
    echo "  --color-${name}-rgb: $(rgb_decimal "$value");"
  done

  # Obsidian's primary interactive accent (buttons, links, checkboxes,
  # active states) is HSL-driven, not part of the --color-base-* ramp -
  # --color-accent is computed from --accent-h/-s/-l elsewhere in core CSS.
  # base0D (blue) is base16's "functions/methods" slot, used here as the
  # general-purpose primary accent - swap the source slot if you'd rather
  # something else drive it.
  if [ -n "$base0D" ]; then
    read -r h s l < <(python3 -c "
import colorsys
hexval = '$base0D'.lstrip('#')
r, g, b = (int(hexval[i:i+2], 16) / 255 for i in (0, 2, 4))
h, l, s = colorsys.rgb_to_hls(r, g, b)
print(round(h * 360), round(s * 100), round(l * 100))
")
    echo "  --accent-h: ${h};"
    echo "  --accent-s: ${s}%;"
    echo "  --accent-l: ${l}%;"
  fi

  echo "}"
} >"$out"
