return {
	-- Treesitter: proper Nix syntax highlighting
	{
		"nvim-treesitter/nvim-treesitter",
		opts = function(_, opts)
			vim.list_extend(opts.ensure_installed, { "nix" })
		end,
	},

	-- LSP: nixd, provided by Nix (extraPackages) - no mason install needed
	{
		"neovim/nvim-lspconfig",
		opts = {
			servers = {
				nixd = {},
			},
		},
	},

	-- Formatter: deadnix (removes dead code) + statix (fixes antipatterns) on
	-- save, then nixfmt last so it cleans up whatever those two touched.
	-- Both edit the file in place rather than via stdin/stdout, hence stdin = false.
	--
	-- hardware-configuration.nix is generated by nixos-generate-config and
	-- carries its own "do not modify" comment - regeneration would blow away
	-- any fixes anyway, so all three formatters skip it.
	{
		"stevearc/conform.nvim",
		opts = {
			formatters = {
				statix = {
					command = "statix",
					args = { "fix", "$FILENAME" },
					stdin = false,
					condition = function(_, ctx)
						return not ctx.filename:match("hardware%-configuration%.nix$")
					end,
				},
				deadnix = {
					command = "deadnix",
					args = { "--edit", "$FILENAME" },
					stdin = false,
					condition = function(_, ctx)
						return not ctx.filename:match("hardware%-configuration%.nix$")
					end,
				},
				nixfmt = {
					condition = function(_, ctx)
						return not ctx.filename:match("hardware%-configuration%.nix$")
					end,
				},
			},
			formatters_by_ft = {
				nix = { "deadnix", "statix", "nixfmt" },
			},
		},
	},

	-- Linters: statix (antipatterns) + deadnix (dead code), run on save/insert-leave
	{
		"mfussenegger/nvim-lint",
		opts = {
			linters_by_ft = {
				nix = { "statix", "deadnix" },
			},
		},
	},
}
