-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

--######################
--## IMPORT NIX VARS ###
--######################
-- Keep this active to use your colors ($activeBorder, etc.)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

require("variables")

--################
--## FILE VARS ###
--################

local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local hs = require("hyprsplit")


-- Hyprsplit config
hs.config({
    num_workspaces = 10,
})

-- Hyprglass configuration
if hl.plugin.hyprglass then
    local hg = hl.plugin.hyprglass

    hg.config({
        default_theme = "dark",
        default_preset = "clear",
        tint_color = 0x8899aa22,

        brightness = 0.9,
        dark = { brightness = 0.82 },
        light = { adaptive_boost = 0.5 },

        layers = { enabled = 1 },
    })

    -- Layer surfaces configuration
    hg.layer("waybar", { preset = "subtle", mask_threshold = 0.05 })
end

hl.bind(mainMod .. " + SHIFT + G", hs.dsp.grab_rogue_windows())

-- Jump focus between monitors (cycle through them)
hl.bind(mainMod .. " + TAB", hl.dsp.focus({ monitor = "+1" }))
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.focus({ monitor = "-1" }))

--##################
--## MY PROGRAMS ###
--##################

local terminal = "kitty"
local fileManager = "nautilus"
local menu = "rofi -show drun -show-icons"
local browser = "firefox"
local notes = "obsidian"
local editor = "code"
local editor_alt = "subl"
local colorPicker = "hyprpicker"

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- Firefox
hl.env("MOZ_ENABLE_WAYLAND", "1")

-- QT
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_STYLE_OVERRIDE", "kvantum")

-- Toolkit Backend Variables
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")

-- XDG Specifications
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.curve("wind", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.01 } } })
hl.curve("winIn", { type = "bezier", points = { { 0.1, 1 }, { 0.1, 1.01 } } })
hl.curve("winOut", { type = "bezier", points = { { 0.3, 0 }, { 0, 1 } } })
hl.curve("liner", { type = "bezier", points = { { 1, 1 }, { 1, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 6,
    bezier = "wind",
    style = "slide",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 6,
    bezier = "winIn",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 5,
    bezier = "winOut",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 5,
    bezier = "wind",
    style = "slide",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1,
    bezier = "liner",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 30,
    bezier = "liner",
    style = "loop",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "wind",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3,
    bezier = "default",
    style = "slidevert",
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Define the helper functions
local function focus_ws(ws_num)
    return function()
        local monitors = hl.get_monitors()
        local monitor_count = #monitors
        if monitor_count > 1 then
            if ws_num <= 5 then
                local monitor = monitors[1]
                if monitor then
                    hl.dispatch(hl.dsp.focus({ monitor = monitor.name }))
                    hl.dispatch(hs.dsp.focus({ workspace = ws_num }))
                end
            else
                local monitor = monitors[2]
                if monitor then
                    hl.dispatch(hl.dsp.focus({ monitor = monitor.name }))
                    hl.dispatch(hs.dsp.focus({ workspace = ws_num - 5 }))
                end
            end
        else
            hl.dispatch(hs.dsp.focus({ workspace = ws_num }))
        end
    end
end

local function move_ws(ws_num)
    return function()
        local monitors = hl.get_monitors()
        local monitor_count = #monitors
        if monitor_count > 1 then
            if ws_num <= 5 then
                local monitor = monitors[1]
                if monitor then
                    hl.dispatch(hl.dsp.window.move({ monitor = monitor.name }))
                    hl.dispatch(hs.dsp.window.move({ workspace = ws_num }))
                end
            else
                local monitor = monitors[2]
                if monitor then
                    hl.dispatch(hl.dsp.window.move({ monitor = monitor.name }))
                    hl.dispatch(hs.dsp.window.move({ workspace = ws_num - 5 }))
                end
            end
        else
            hl.dispatch(hs.dsp.window.move({ workspace = ws_num }))
        end
    end
end

-- Create a function that builds the binds based on current hardware
local function setup_workspace_binds()
    local monitors = hl.get_monitors()
    local monitor_count = #monitors

    -- 1-5 Binds
    for i = 1, 5 do
        local n = tostring(i)
        hl.bind(mainMod .. " + " .. n, focus_ws(i))
        hl.bind(mainMod .. " + SHIFT + " .. n, move_ws(i))
    end

    -- 6-0 Binds (Only if multi-monitor)
    if monitor_count > 1 then
        for i = 6, 10 do
            local n = (i == 10) and "0" or tostring(i)
            hl.bind(mainMod .. " + " .. n, focus_ws(i))
            hl.bind(mainMod .. " + SHIFT + " .. n, move_ws(i))
        end
    end
end

setup_workspace_binds()

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hs.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hs.dsp.focus({ workspace = "e-1" }))

-- Switch workspaces with mainMod + mouse side buttons (back/forward)
hl.bind(mainMod .. " + mouse:275", hs.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:276", hs.dsp.focus({ workspace = "e+1" }))

--  Row 2 (Q W E R T Y U I O P) 
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(editor))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(notes))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(colorPicker .. " | wl-copy"))

--  Row 3 (A S D F G H J K L) 
hl.bind(mainMod .. " + A", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("/home/jacob/.config/hypr/scripts/toggle_special.sh"))
hl.bind(mainMod .. " + CTRL + A", hl.dsp.exec_cmd("/home/jacob/.config/hypr/scripts/toggle_workspace_special.sh"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + G", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("systemd-run --user systemctl suspend"))

--  Row 4 (Z X C V B N M) 
hl.bind(mainMod .. " + Z", hl.dsp.window.drag())
hl.bind(mainMod .. " + X", hl.dsp.window.resize())
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | tofi -c ~/.config/tofi/configV | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + M", hl.dsp.exit())

--  Special Keys & Mouse 
hl.bind("SUPER + ESCAPE", hl.dsp.exec_cmd("wlogout"))
hl.bind("CTRL + Escape", hl.dsp.exec_cmd("killall waybar || waybar"))
hl.bind(mainMod .. " + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.center())

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Move window position with mainMod + SHIFT + arrow keys
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Resize windows with mainMod + CTRL + arrow keys
-- Resize windows with mainMod + CTRL + arrow keys
hl.bind(mainMod .. " + CTRL + Right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + Left", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + Up", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + Down", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })

-- Screenshot
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("SUPER + Print", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("SUPER + ALT + Print", hl.dsp.exec_cmd("hyprshot -m output"))

-- Volume and Media Control
hl.bind(mainMod .. " + F11", hl.dsp.exec_cmd("/home/jacob/.config/hypr/scripts/toggle_audio.sh"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.window_rule({
    match = {
        class = "org.gnome.Calendar",
    },
    float = true,
    center = true,
    size = "800 650",
})

hl.config({
    general = {
        gaps_in = 2.5,
        gaps_out = 5,
        border_size = borderSize,
        
        -- https://wiki.hypr.land/Configuring/Basics/Variables/ for info about colors
        ["col.active_border"] = activeBorder,
        ["col.inactive_border"] = inactiveBorder,
        
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
    
    -- https://wiki.hypr.land/Configuring/Variables/#decoration
    decoration = {
        rounding = rounding,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.9,
        inactive_opacity = 0.85,
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 2,
            passes = 3,
            new_optimizations = true,
            vibrancy = 0.1696,
            ignore_opacity = true,
            xray = true,
        },
    },
    
    -- https://wiki.hypr.land/Configuring/Variables/#animations
    animations = {
        enabled = true,
    },
    
    -- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
    dwindle = {
        -- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below (removed in Hyprland v0.55)
        preserve_split = true, -- You probably want this
    },
    
    -- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
    master = {
        --  OLD CONFIG 
        -- new_status = master
    },
    
    -- https://wiki.hypr.land/Configuring/Variables/#misc
    --  NEW CONFIG 
    misc = {
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = true,
        vrr = 0,
        initial_workspace_tracking = 1,
        animate_manual_resizes = true,
    },

    cursor = {
        no_hardware_cursors = true,
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hypr.land/Configuring/Variables/#input
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:super",
        kb_rules = "",

        follow_mouse = 1,
        -- force_no_accel = 1
        
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        
        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("ags")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprlock")
end)

